#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.2
# from Racc grammar file "".
#

require 'racc/parser.rb'
module JsonEncoder
  class Parser < Racc::Parser


require "json_encoder/handler"

attr_reader :handler

def initialize(tokenizer, handler = Handler.new)
  @tokenizer = tokenizer
  @handler   = handler
  super()
end

def next_token
  @tokenizer.next_token
end

def parse
  do_parse
  handler
end
##### State transition tables begin ###

racc_action_table = [
    12,    13,    14,    15,    16,    17,     6,    21,    32,     8,
    12,    13,    14,    15,    16,    17,     6,    26,    18,     8,
    12,    13,    14,    15,    16,    17,     6,    26,    35,     8,
    12,    13,    14,    15,    16,    17,     6,    12,    30,     8,
    33,    12,   nil,   nil,    21 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,    20,    20,     0,
     7,     7,     7,     7,     7,     7,     7,     7,     1,     7,
    33,    33,    33,    33,    33,    33,    33,    25,    25,    33,
    35,    35,    35,    35,    35,    35,    35,     5,    18,    35,
    23,    32,   nil,   nil,     5 ]

racc_action_pointer = [
    -2,    18,   nil,   nil,   nil,    35,   nil,     8,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    38,   nil,
    -2,   nil,   nil,    30,   nil,    18,   nil,   nil,   nil,   nil,
   nil,   nil,    39,    18,   nil,    28,   nil,   nil,   nil ]

racc_action_default = [
   -28,   -28,    -1,    -2,    -3,   -28,    -6,   -28,   -13,   -17,
   -20,   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,    -4,
   -28,    -7,    -9,   -28,   -11,   -28,   -14,   -16,   -18,   -19,
    39,    -5,   -28,   -28,   -12,   -28,    -8,   -10,   -15 ]

racc_goto_table = [
     4,    22,    23,    24,    19,     1,     2,    27,     3,    20,
    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    31,
   nil,    34,   nil,   nil,   nil,   nil,   nil,   nil,    36,    23,
   nil,   nil,   nil,    37,   nil,    38 ]

racc_goto_check = [
     4,     8,     9,    11,     6,     1,     2,     4,     3,     7,
    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,
   nil,    11,   nil,   nil,   nil,   nil,   nil,   nil,     8,     9,
   nil,   nil,   nil,     4,   nil,     4 ]

racc_goto_pointer = [
   nil,     5,     6,     8,     0,   nil,    -1,     4,    -4,    -3,
   nil,    -4,     3,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    28,    29,   nil,     5,   nil,   nil,   nil,    10,
     7,   nil,   nil,     9,    11 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  2, 14, :_reduce_none,
  3, 14, :_reduce_none,
  1, 17, :_reduce_6,
  1, 18, :_reduce_7,
  3, 19, :_reduce_none,
  1, 19, :_reduce_none,
  3, 20, :_reduce_none,
  2, 15, :_reduce_none,
  3, 15, :_reduce_none,
  1, 22, :_reduce_13,
  1, 23, :_reduce_14,
  3, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_21,
  1, 21, :_reduce_22,
  1, 26, :_reduce_23,
  1, 26, :_reduce_24,
  1, 26, :_reduce_25,
  1, 26, :_reduce_26,
  1, 26, :_reduce_27 ]

racc_reduce_n = 28

racc_shift_n = 39

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :INTEGER => 3,
  :FLOAT => 4,
  :TRUE => 5,
  :FALSE => 6,
  :NULL => 7,
  "*" => 8,
  "+" => 9,
  "." => 10,
  "-" => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "INTEGER",
  "FLOAT",
  "TRUE",
  "FALSE",
  "NULL",
  "\"*\"",
  "\"+\"",
  "\".\"",
  "\"-\"",
  "$start",
  "document",
  "object",
  "array",
  "value",
  "start_object",
  "end_object",
  "pairs",
  "pair",
  "string",
  "start_array",
  "end_array",
  "values",
  "scalar",
  "literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
@handler.start_object
    result
end

def _reduce_7(val, _values, result)
@handler.end_object
    result
end

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

def _reduce_13(val, _values, result)
@handler.start_array
    result
end

def _reduce_14(val, _values, result)
@handler.end_array
    result
end

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

def _reduce_21(val, _values, result)
@handler.scalar(val[0])
    result
end

def _reduce_22(val, _values, result)
@handler.scalar(val[0])
    result
end

def _reduce_23(val, _values, result)
result = val[0].to_i
    result
end

def _reduce_24(val, _values, result)
result = val[0].to_f
    result
end

def _reduce_25(val, _values, result)
result = true
    result
end

def _reduce_26(val, _values, result)
result = false
    result
end

def _reduce_27(val, _values, result)
result = nil
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module JsonEncoder
